spring:
  application:
    name: colab-v1
  main:
    banner-mode: OFF
  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix: .html
    mode: HTML
    cache: false
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
  sql:
    init:
      mode: EMBEDDED
      schema-locations:
        - classpath:sql/h2/schema.sql
  h2:
    console:
      path: /h2-console
      enabled: true


mybatis:
  configuration:
    lazy-loading-enabled: true
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    cache-enabled: false
    local-cache-scope: STATEMENT
    jdbc-type-for-null: NULL
  type-aliases-package: com.bincui.colab.domain.**.dto
  type-handlers-package: com.bincui.colab.global.common.type
  mapper-locations:
    - classpath:mappers/*_mapper.xml

server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true